name: Keystroke Dynamics apk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Set up Flutter with the required version (3.3.4 or higher)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"  # Update to match the required Dart SDK version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze the project source code
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Build the APK for release
      - name: Build APK
        run: flutter build apk --release

      # Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
