name: iOS-Keystroke-Dynamics

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Keystroke_Dynamics
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Clear the pub cache to avoid old dependencies
      - name: Clear Pub Cache
        run: flutter pub cache clean

      # Override win32 dependency
      - name: Set Dependency Overrides
        run: |
          echo 'dependency_overrides:' >> pubspec.yaml
          echo '  win32: ^5.5.4' >> pubspec.yaml

      # Run Flutter Pub Get
      - run: flutter pub get

      # Update CocoaPods repo
      - run: pod repo update
        working-directory: ios

      # Build the iOS app
      - run: flutter build ios --release --no-codesign

      # Prepare app for export
      - run: mkdir Payload
        working-directory: build/ios/iphoneos
      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Zip the output
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload binaries to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"

